---
title: "Replicate the Original Results using Linear Regression and Mixed-effects Model"
author: "Jie Zhou"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: show
editor_options: 
  
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forestplot)
library(dplyr)
library(DBI)
library(DT)
library(ggplot2)
library(ggrepel)
library(mixOmics)
library(stringr)
library(VCA)
library(nlme)
library(danovir)
source("./code/data_cleaning_no_buffer.R")
source("./code/contrast.R")
options(useFancyQuotes = FALSE)
par(mar=c(1,1,1,1))
```



```{r,echo=FALSE}
library(RColorBrewer)
# colors=c("#E04C5C","#7DAF4C","#23AECE", "#FB894B", "#E7DA36",  "#187A51",
#          "#5EA4A2",  "#3D3C4E", "#4D1836", "#C51B7D",
#          "#E9A3C9",  "#B35806", "#F1A340", "#FEE08B", "#D9EF8B",
#          "#91CF60", "#C7EAE5", "#5AB4AC", "#01665E", "#E7D4E8",
#          "#AF8DC3", "#762A83","#FC0FC0","#F9C7DE","#f3a0c4")
# names(colors)=c("IgA2",      "IgA1",      "FcaR",      "FcgR2A131", "FcgR3A158", "IgG" ,      "ELISA IgG", "IgG4",      "IgG2",      "IgA"  ,     "IgG3"  ,    "IgM"    ,   "FcgR1A"  ,  "MN"    ,    "FcgR2b"  ,  "IgG1" ,
#  "HAI",       "NAI"  ,     "FcgR3b","ADCC","ADCP","ADCD")
colors = c(IgG = "#1e90ff",

                   IgA = "#3f007d",

                   IgA1 = "#C7EAE5",

                   IgA2 = "#9e9ac8",

                   IgD = "#662506",

                   IgM = "#8b7765",

                   IgG1 = "#C6E2FF",

                   IgG2 = "#CC3232",

                   IgG3 = "#4F94CD",

                   IgG4 = "#1D3700",

                   FcgR2A131 = "#157B74",

                   FcgR2b = "#CDCD00",

                   FcgR3A158 = "#722841",

                   FcgR3b = "#23AECE",

                   FcaR = "#bcbddc",
            FcRn = "#7B5D56",

                   Func="#000000",
           
           ADCC= "#80CBC4",
           ADCP="#A5D6A7",
           ADCD="#2166AC",
           MN= "#23AECE",
           HAI=  "#C7EAE5",
           NAI=  "#5AB4AC",
          "ELISA IgG"= "#7DAF4C",
           CA07="#1B4F72",
            FcgR2B = "#CDCD00",
           FcgR1A="#AA4371",

                   FcgR3A = "#722841",

                   FcgR3B = "#23AECE",
           FcgR2A = "#458B74",
          
 "ELISA"= "#7DAF4C"
           )
```





```{r,warning=FALSE,echo=FALSE}
## exclude non Lumbaa assay
device=do.call(rbind,strsplit(combined_experiments$detect_method,split="_"))
combined_experiments=cbind(combined_experiments,assay=device[,1])
 index=which(device[,1]=="LumBAA" | device[,1]=="NAI" | device[,1]=="MN" | device[,1]=="HAI" | device[,1]=="ELISA"
               | device[,1]=="ADCC" | device[,1]=="ADCP" | (device[,1]=="ADCD" & device[,3]=="dil3200" & device[,2]=="set1" ))

combined_experiments=combined_experiments[index,]
index=which(combined_experiments$detect_method=="ADCD_set1_dil3200")
combined_experiments$detect_method[index]="ADCD"



## exclude non ca data
 index=grep("CA",combined_experiments$analyte_reported)
 combined_experiments=combined_experiments[index,]
 ## exclude HA_dtm
 index=which(combined_experiments$analyte_type=="HA_dTM")
 combined_experiments=combined_experiments[-index,]
## create features
temp = paste(combined_experiments$assay, combined_experiments$analyte_reported, sep="_")
temp=ifelse(temp=="NAI_NAI_CA07","NAI_CA07", ifelse(temp=="MN_MN_CA07","MN_CA07",ifelse(temp=="HAI_HAI_CA07","HAI_CA07",
  ifelse(temp=="ADCC_ADCC_CA07","ADCC_CA07",ifelse(temp=="ADCP_ADCP_CA07","ADCP_CA07",
                                                   ifelse(temp=="ADCD_ADCD_CA07_HA","ADCD_CA07_HA",ifelse(temp=="ADCD_ADCD_CA07_HA_FL","ADCD_CA07_HA_FL",ifelse(temp=="ADCD_ADCD_CA07_HA_stalk","ADCD_CA07_HA_stalk",ifelse(temp=="ADCD_ADCD_CA07_NA","ADCD_CA07_NA",temp)))))))))
combined_experiments$temp=temp
## for each assay, assign a shape number for plotting in the following. 
assay=unique(combined_experiments$assay)
shapes=c(15,17,18)
names(shapes)=c("HASK",        "NA",         "HAFL")
```


```{r,echo=FALSE}
index=which(combined_experiments$arm_name=="Non-Pregnant 15 mcg" | combined_experiments$visit_name=="Delivery Visit" | combined_experiments$visit_name=="Visit 1 (Pre-vaccination)")
data15=combined_experiments[-index,]
 index=which(data15$assay %in% c("LumBAA","ADCD","ELISA"))
 data15=data15[index,]
data15$arm=ifelse(data15$arm_name=="Pregnant 15 mg","P15","P30")
data15$antigen= ifelse(data15$analyte_type=="HA","HA",ifelse(data15$analyte_type=="HA_FL","HAFL", ifelse(data15$analyte_type=="HA_stalk","HASK",ifelse(data15$analyte_type=="live_virus", "LV","NA"))))
data15$value_reported=log2(data15$value_reported+1)
data15$antigen=factor(data15$antigen,levels = c("NA","HA","HAFL","HASK"))
data15$detect_reagent=factor(data15$detect_reagent,levels=c("IgG", "FcaR",       "FcgR1A", "FcgR2A131", "FcgR2b", "FcgR3A158", "FcgR3b", "IgA", "IgA1", "IgA2", "IgG1", "IgG2", "IgG3", "IgG4", "IgM"))
index=which(data15$antigen=="HA")
data15=data15[-index,]
data15$antigen=droplevels(data15$antigen)
```


```{r,echo=FALSE}

data15$sub001=ifelse(data15$subject_accession=="SUB8888001",1,0)

varPlot(form = value_reported~ arm+antigen+detect_reagent+assay, Data=data15,MeanLine=list(var=c("int", "arm", "antigen"), 
                      col=c("white", "blue", "magenta"), lwd=c(2,2,2)),
        BG=list(var="antigen", col=paste0("gray", c(70,80,90))),
        Points=list(pch=list(var="sub001", pch=c(15, 21)),
                    col=list(var="sub001", col=c("green", "black")),
                    #bg= list(var="sub001", #bg=c("yellow","white")),
                    cex=list(var="sub001", cex=c(0.6, 0.3))
                    ),
        VarLab=list(list(cex=1), list(cex=1),
                    list(cex=0.15, srt=1), list(cex=0.15)),
        YLabel=list(text="log10(value+1)(MFI)", las=0, line=3, font=2, cex=1.25),
    Title=list(main="Pregnancy", cex.main=1.75)
        )
data15=groupedData(value_reported~arm|subject_accession,data=data15)
data15$feature=paste0(data15$antigen,data15$detect_reagent,sep="")
contr=lmeControl(maxIter = 100,msMaxIter = 100,niterEM = 100)
```


### Mode 1 : third order model + independent error + feature-specific variance


$$infant_{ijkl}=\mu +  \alpha_j + \beta_k + \lambda_l+\gamma_{1lj}+\gamma_{2lk}+ \gamma_{3jk}+\gamma_{jkl}+ e_{ijk}, e_{ijk}\sim N(0,\sigma_{jk})$$




```{r,message=FALSE,echo=FALSE}
mainEffect2=gls(value_reported~arm+ antigen+detect_reagent+assay+ arm:antigen+arm:detect_reagent+antigen:detect_reagent+arm:antigen:detect_reagent,data = data15 ,weights = varIdent(form=~1|feature),method = "ML")
aa=summary(mainEffect2)
```

```{r,echo=FALSE,message=FALSE}
sele=list(antigen=c(2,21,22),detect_reagent=c(2,23:36),three=c(2,65:92))
names(sele$antigen)=levels(data15$antigen)
names(sele$detect_reagent)=levels(data15$detect_reagent)
coeVec=aa$coefficients
varMatrix=aa$varBeta
bb=contrast(sele=sele,coeVec = coeVec,varMatrix = varMatrix)
print("Effects of maternal immunization on features (antigen+analyte):  ")
```


### Model 2: third order model + random intercept + heteroscedastic error


$$infant_{ijkl}=\mu +  \alpha_j + \beta_k + \lambda_l+\gamma_{1lj}+\gamma_{2lk}+ \gamma_{3jk}+\gamma_{4jkl}+u_i+ e_{ijk}, e_{ijk}\sim N(0,\sigma_{jk})$$

```{r,message=FALSE,echo=FALSE}
mainEffect3=lme(value_reported~arm+ feature+assay+ arm:feature,random=pdDiag(~1),weights = varIdent(form = ~1|feature),data = data15,method = "ML",control = contr)
aa=summary(mainEffect3)
```

