---
title: "Simulatioon Studies of decomposition model: 5 antigens with 6 antibodies"
author: "Jie Zhou"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: show
editor_options: 
  
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forestplot)
library(dplyr)
library(DBI)
library(DT)
library(ggplot2)
library(ggrepel)
library(mixOmics)
library(stringr)
library(VCA)
library(nlme)
library(devtools)
library(glmmLasso)
load_all("C:/Users/Jie Zhou/Desktop/danovir")
source("./code/contrast.R")
source("./code/simulation.R")
options(useFancyQuotes = FALSE)
par(mar=c(2,2,2,2))
set.seed(10)
```


Model:

$$infant_{ijkl}=\mu +  \alpha_j + \beta_k + \lambda_l+\gamma_{1lj}+\gamma_{2lk}+ \gamma_{3jk}+\gamma_{jkl}+ e_{ijk}, e_{ijk}\sim N(0,\sigma_{jk})$$





## 1. data are from full model with independent repeated measurements 

```{r,message=FALSE,echo=FALSE}
for (esd in c(0.6,1,1.5)) {
sd=c(0.5,0.5,0.5,1,1,2,1,1,1,esd)
#sd=rep(0.01,10)
names(sd)=c("Trag","Trab","Tragab","Ag","Ab","Agab","Rdin","Rdag","Rdab","Error")
simResults=geneData(N=40,Nag=5,Nab=6,sd=sd,type=1)
data15=simResults$data[which(simResults$data$trainLabel=="training"),]
data15$feature=paste(data15$antigen,data15$antibody,sep = "_")
mainEffect1=danovir(data=data15,type=1)
mainEffect3=danovir(data=data15,nfold=10,nlambda=100,type=3)

testing=simResults$data[which(simResults$data$trainLabel=="testing"),]
MM=model.matrix(mainEffect1$formula,data = testing)
Pstandard= MM%*%(mainEffect1$fixedStandard$coeVec)
Pdecomposed= MM%*%(mainEffect1$fixedDecomposed$coeVec)
Pdenoised= MM%*%(mainEffect3$fixedDecomposed$coeVec)
extdata1=cbind(testing,Pstandard,Pdecomposed,Pdenoised)
pmse1=mean((extdata1$response-extdata1$Pstandard)^2)
pmse2=mean((extdata1$response-extdata1$Pdecomposed)^2)
pmse3=mean((extdata1$response-extdata1$Pdenoised)^2)
mse1=mean((c(simResults$effects)-mainEffect1$benchmark$effects)^2)
mse2=mean((c(simResults$effects)-mainEffect1$selected$effects)^2)
mse3=mean((c(simResults$effects)-mainEffect3$selected$effects)^2)
ee1= mean((mainEffect1$fixedStandard$coeVec-simResults$coef)^2)
ee2= mean((mainEffect1$fixedDecomposed$coeVec-simResults$coef)^2)
ee3= mean((mainEffect3$fixedDecomposed$coeVec-simResults$coef)^2)


pmse=c(pmse1,pmse2,pmse3)
names(pmse)=c("standard","random intercept","dnoised")
print(paste0("MSE for testing data: "))
print(round(pmse,3))
mse=c(mse1,mse2,mse3)
names(mse)=c("standard","random intercept","dnoised")
print("MSE for treatment effect estimates: ")
print(round(mse,3))
ee=c(ee1,ee2,ee3)
names(ee)=c("standard","random intercept","dnoised")
print("MSE for coefficient estimates: ")
print(round(ee,3))
##
par(mfrow=c(1,3))
x0=range(simResults$effects)
y0=range(mainEffect1$benchmark$effects,mainEffect1$selected$effects,
        mainEffect3$selected$effects)
plot(simResults$effects,mainEffect1$benchmark$effects,xlim = x0,ylim = y0,xlab="True value",ylab="Difference of mean")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("standard")

plot(simResults$effects,mainEffect1$selected$effects,xlim = x0,ylim = y0,xlab="True value",ylab="random intercept")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("random intercept")


plot(simResults$effects,mainEffect3$selected$effects,xlim = x0,ylim = y0,xlab="True value",ylab="Denoised value")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("denoised")
}
```



## 2. data are from full model with random intercepts 

```{r,message=FALSE,echo=FALSE}
for (esd in c(0.6,1,1.5)) {
sd=c(0.5,0.5,0.5,1,1,2,1,1,1,esd)
#sd=rep(0.01,10)
names(sd)=c("Trag","Trab","Tragab","Ag","Ab","Agab","Rdin","Rdag","Rdab","Error")
simResults=geneData(N=40,Nag=5,Nab=6,sd=sd,type=2)
data15=simResults$data
data15$feature=paste(data15$antigen,data15$antibody,sep = "_")
mainEffect1=danovir(data=data15,type=1)
mainEffect3=danovir(data=data15,nfold=10,nlambda=100,type=3)

testing=simResults$data[which(simResults$data$trainLabel=="testing"),]
MM=model.matrix(mainEffect1$formula,data = testing)
Pstandard= MM%*%(mainEffect1$fixedStandard$coeVec)
Pdecomposed= MM%*%(mainEffect1$fixedDecomposed$coeVec)
Pdenoised= MM%*%(mainEffect3$fixedDecomposed$coeVec)
extdata1=cbind(testing,Pstandard,Pdecomposed,Pdenoised)
pmse1=mean((extdata1$response-extdata1$Pstandard)^2)
pmse2=mean((extdata1$response-extdata1$Pdecomposed)^2)
pmse3=mean((extdata1$response-extdata1$Pdenoised)^2)

mse1=mean((c(simResults$effects)-mainEffect1$benchmark$effects)^2)
mse2=mean((c(simResults$effects)-mainEffect1$selected$effects)^2)
mse3=mean((c(simResults$effects)-mainEffect3$selected$effects)^2)
ee1= mean((mainEffect1$fixedStandard$coeVec-simResults$coef)^2)
ee2= mean((mainEffect1$fixedDecomposed$coeVec-simResults$coef)^2)
ee3= mean((mainEffect3$fixedDecomposed$coeVec-simResults$coef)^2)



pmse=c(pmse1,pmse2,pmse3)
names(pmse)=c("standard","random intercept","dnoised")
print(paste0("MSE for testing data: "))
print(round(pmse,3))
mse=c(mse1,mse2,mse3)
names(mse)=c("standard","random intercept","dnoised")
print("MSE for treatment effect estimates: ")
print(round(mse,3))
ee=c(ee1,ee2,ee3)
names(ee)=c("standard","random intercept","dnoised")
print("MSE for coefficient estimates: ")
print(round(ee,3))
##
par(mfrow=c(1,3))
x0=range(simResults$effects)
y0=range(mainEffect1$benchmark$effects,mainEffect1$selected$effects,
        mainEffect3$selected$effects)
plot(simResults$effects,mainEffect1$benchmark$effects,xlim = x0,ylim = y0,xlab="True value",ylab="Difference of mean")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("standard")

plot(simResults$effects,mainEffect1$selected$effects,xlim = x0,ylim = y0,xlab="True value",ylab="random intercept")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("random intercept")


plot(simResults$effects,mainEffect3$selected$effects,xlim = x0,ylim = y0,xlab="True value",ylab="Denoised value")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("denoised")
}
```



## 3. data are from full model with  random intercept and antigen effects

```{r,message=FALSE,echo=FALSE}
for (esd in c(0.6,1,1.5)) {
sd=c(0.5,0.5,0.5,1,1,2,1,1,1,esd)
#sd=rep(0.01,10)
names(sd)=c("Trag","Trab","Tragab","Ag","Ab","Agab","Rdin","Rdag","Rdab","Error")
simResults=geneData(N=40,Nag=5,Nab=6,sd=sd,type=3)
data15=simResults$data
data15$feature=paste(data15$antigen,data15$antibody,sep = "_")
mainEffect1=danovir(data=data15,type=2)
mainEffect3=danovir(data=data15,nfold=10,nlambda=100,type=3)

testing=simResults$data[which(simResults$data$trainLabel=="testing"),]
MM=model.matrix(mainEffect1$formula,data = testing)
Pstandard= MM%*%(mainEffect1$fixedStandard$coeVec)
Pdecomposed= MM%*%(mainEffect1$fixedDecomposed$coeVec)
Pdenoised= MM%*%(mainEffect3$fixedDecomposed$coeVec)
extdata1=cbind(testing,Pstandard,Pdecomposed,Pdenoised)
pmse1=mean((extdata1$response-extdata1$Pstandard)^2)
pmse2=mean((extdata1$response-extdata1$Pdecomposed)^2)
pmse3=mean((extdata1$response-extdata1$Pdenoised)^2)

mse1=mean((c(simResults$effects)-mainEffect1$benchmark$effects)^2)
mse2=mean((c(simResults$effects)-mainEffect1$selected$effects)^2)
mse3=mean((c(simResults$effects)-mainEffect3$selected$effects)^2)
ee1= mean((mainEffect1$fixedStandard$coeVec-simResults$coef)^2)
ee2= mean((mainEffect1$fixedDecomposed$coeVec-simResults$coef)^2)
ee3= mean((mainEffect3$fixedDecomposed$coeVec-simResults$coef)^2)



pmse=c(pmse1,pmse2,pmse3)
names(pmse)=c("standard","random intercept/antigen","dnoised")
print(paste0("MSE for testing data: "))
print(round(pmse,3))
mse=c(mse1,mse2,mse3)
names(mse)=c("standard","random intercept/antigen","dnoised")
print("MSE for treatment effect estimates: ")
print(round(mse,3))
ee=c(ee1,ee2,ee3)
names(ee)=c("standard","random intercept/antigen","dnoised")
print("MSE for coefficient estimates: ")
print(round(ee,3))
##
par(mfrow=c(1,3))
x0=range(simResults$effects)
y0=range(mainEffect1$benchmark$effects,mainEffect1$selected$effects,
        mainEffect3$selected$effects)
plot(simResults$effects,mainEffect1$benchmark$effects,xlim = x0,ylim = y0,xlab="True value",ylab="Difference of mean")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("standard")

plot(simResults$effects,mainEffect1$selected$effects,xlim = x0,ylim = y0,xlab="True value",ylab="random intercept")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("random intercept/antigen")


plot(simResults$effects,mainEffect3$selected$effects,xlim = x0,ylim = y0,xlab="True value",ylab="Denoised value")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("denoised")
}
```



## 4. data are from full model with  random intercept and antigen effects

```{r,message=FALSE,echo=FALSE}
for (esd in c(0.6,1,1.5)) {
sd=c(0.5,0.5,0.5,1,1,2,1,1,1,esd)
#sd=rep(0.01,10)
names(sd)=c("Trag","Trab","Tragab","Ag","Ab","Agab","Rdin","Rdag","Rdab","Error")
simResults=geneData(N=40,Nag=5,Nab=6,sd=sd,type=3)
data15=simResults$data
data15$feature=paste(data15$antigen,data15$antibody,sep = "_")
mainEffect1=danovir(data=data15,type=1)
mainEffect3=danovir(data=data15,nfold=10,nlambda=100,type=3)

testing=simResults$data[which(simResults$data$trainLabel=="testing"),]
MM=model.matrix(mainEffect1$formula,data = testing)
Pstandard= MM%*%(mainEffect1$fixedStandard$coeVec)
Pdecomposed= MM%*%(mainEffect1$fixedDecomposed$coeVec)
Pdenoised= MM%*%(mainEffect3$fixedDecomposed$coeVec)
extdata1=cbind(testing,Pstandard,Pdecomposed,Pdenoised)
pmse1=mean((extdata1$response-extdata1$Pstandard)^2)
pmse2=mean((extdata1$response-extdata1$Pdecomposed)^2)
pmse3=mean((extdata1$response-extdata1$Pdenoised)^2)

mse1=mean((c(simResults$effects)-mainEffect1$benchmark$effects)^2)
mse2=mean((c(simResults$effects)-mainEffect1$selected$effects)^2)
mse3=mean((c(simResults$effects)-mainEffect3$selected$effects)^2)
ee1= mean((mainEffect1$fixedStandard$coeVec-simResults$coef)^2)
ee2= mean((mainEffect1$fixedDecomposed$coeVec-simResults$coef)^2)
ee3= mean((mainEffect3$fixedDecomposed$coeVec-simResults$coef)^2)



pmse=c(pmse1,pmse2,pmse3)
names(pmse)=c("standard","random intercept","dnoised")
print(paste0("MSE for testing data: "))
print(round(pmse,3))
mse=c(mse1,mse2,mse3)
names(mse)=c("standard","random intercept","dnoised")
print("MSE for treatment effect estimates: ")
print(round(mse,3))
ee=c(ee1,ee2,ee3)
names(ee)=c("standard","random intercept","dnoised")
print("MSE for coefficient estimates: ")
print(round(ee,3))
##
par(mfrow=c(1,3))
x0=range(simResults$effects)
y0=range(mainEffect1$benchmark$effects,mainEffect1$selected$effects,
        mainEffect3$selected$effects)
plot(simResults$effects,mainEffect1$benchmark$effects,xlim = x0,ylim = y0,xlab="True value",ylab="Difference of mean")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("standard")

plot(simResults$effects,mainEffect1$selected$effects,xlim = x0,ylim = y0,xlab="True value",ylab="random intercept")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("random intercept")


plot(simResults$effects,mainEffect3$selected$effects,xlim = x0,ylim = y0,xlab="True value",ylab="Denoised value")
abline(a=0,b=1)
legend(x0[1],y0[2],paste0("sd(error)=",esd))
title("denoised")
}
```

## Forest plot


```{r,echo=FALSE,eval=FALSE}
ss=as.data.frame(aa$tTable[c(sele[[1]],sele[[2]][-1],sele[[3]][-1]),c(1,2)])
ss$lower=ss[,1]-1.96*ss[,2]
ss$upper=ss[,1]+1.96*ss[,2]
ss$name=rownames(ss)
rownames(ss)=c()
```

```{r,echo=FALSE,eval=FALSE}
base_data=tibble::tibble(mean=ss$Value,lower=ss$lower,upper=ss$upper,interaction=substr(ss$name,14,nchar(ss$name)))
base_data$interaction=c("ref:na+igg","HAFL","HASK",substr(ss$name[4:17],22,nchar(ss$name[4:17])),paste(substr(ss$name[18:45],15,18),substr(ss$name[18:45],34,50),sep =":"))
```




```{r,echo=FALSE,eval=FALSE}
ss2=as.data.frame(aa$tTable[c(3:18,37:64),c(1,2)])
ss2$lower=ss2[,1]-1.96*ss2[,2]
ss2$upper=ss2[,1]+1.96*ss2[,2]
ss2$name=rownames(ss2)
rownames(ss2)=c()
```

```{r,echo=FALSE,eval=FALSE}
base_data2=tibble::tibble(mean=ss2$Value,lower=ss2$lower,upper=ss2$upper,interaction=substr(ss2$name,14,nchar(ss2$name)))
base_data2$interaction=c("HAFL","HASK",substr(ss2$name[4:17],nchar(ss2$name[4:17])-3,nchar(ss2$name[4:17])),paste(substr(ss2$name[18:45],8,11),substr(ss2$name[18:45],27,50),sep =":"))
```





```{r,echo=FALSE,eval=FALSE}
base_data3=rbind(base_data,base_data2)
```

```{r,echo=FALSE,eval=FALSE}
base_data3 |>
  forestplot(labeltext = c(interaction),txt_gp=fpTxtGp(cex=0.1,label = gpar(fontfamily = "HersheySerif")),
             clip = c(-6, 6)) |>
  fp_set_style(box = "royalblue",
               line = "darkblue",
               summary = "royalblue") |> 
  fp_add_header(interaction= c("Direct effects")) |>
  # fp_append_row(mean  = 0.531,
  #               lower = 0.386,
  #               upper = 0.731,
  #               study = "Summary",
  #               OR = "0.53",
  #               is.summary = TRUE) |>
  fp_set_zebra_style("#EFEFEF")
```




